### ISSUE TITLE
Save h5 files with extension by default

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik4ij#10]
> When exporting to h5 from the Fiji plugin on Windows (at least), the files are saved without extension and are thus not visible in the ilastik open dataset dialog.

superseeds: https://github.com/ilastik/ilastik/issues/1867

**Comment by wolny** [comment]
Fixed in https://github.com/ilastik/ilastik4ij/pull/11: if the '.h5' suffix is not present the error popup will be displayed asking the user to explicitly add it.
