### ISSUE TITLE
Current version installs jars, both in `jars` and `plugins` folder

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik4ij#109]
I probably did something wrong when I uploaded the last version...

<img width="537" alt="image" src="https://github.com/ilastik/ilastik4ij/assets/24434157/5a43e77a-90cc-429e-a30a-c2390d3e132c">

**Comment by emilmelnikov** [comment]
Sorry this was my mistake: apparently, `plugins` should contain actual plugins, while `jars` is the place for your dependencies. It was fixed in https://github.com/ilastik/ilastik4ij/commit/31528dba5413ad7b593f38217560e4790da23c0a.
