### ISSUE TITLE
Configure ilastik executable location dialogue has path from a developer's machine

### ISSUE THREAD

**Issue by nickholway** [ilastik/ilastik4ij#2]
The Configure ilastik executable location dialogue has a path from a developer's machine, "/Users/chaubold/Desktop/ilastik-1.2.0-OSX.app" 

I'm using 1.0.5 of the plugin.

**Comment by akreshuk** [comment]
Between the plugins from ilastik there is one called "configure the ilastik executable location", so you can change it there to your path. But I admit the current way is clumsy, we should make it more straight-forward.
