### ISSUE TITLE
LogService

### ISSUE THREAD

**Issue by tischi** [ilastik/ilastik4ij#28]
@wolny 
I am leaning towards going back to simply using the `LogService` to reduce the complexity of the code. In the end this is meant for usage in ImageJ anyway and it is actually quite easy to get a `LogService`:
```
final ImageJ ij = new ImageJ();
final LogService logService =  ij.log();
```
This is arguably easier than finding our `LogServiceWrapper` class.

**Comment by tischi** [comment]
...would it be OK for you if I did that?

**Comment by wolny** [comment]
Hey @tischi, I totally agree. It will be less clutter in the code and since you use it in from the ImageJ anyway there we shouldn't sweat too much to make the API generic
