### ISSUE TITLE
autocontext 2-stage small images

### ISSUE THREAD

**Issue by gldjck** [ilastik/ilastik4ij#33]
Hi, I have an issue when using Autocontext 2-stage. My input data are separate 2D 8-bit images with different sizes. When trying to add images that are smaller as 9KB, I get this message: 'AutocontextTwoStage' object has no attribute 'featureSelectionApplet' and they won't load. For larger images it works fine. Is there a workaround?

**Comment by k-dominik** [comment]
Hi @gldjck,

could you please add a little more detail to this issue?

**Comment by gldjck** [comment]
Hi @k-dominik,
I finally found the issue, the images I was importing for the auto context 2 stage where too small for the filters I selected.
Cheers,
Ella
