### ISSUE TITLE
hdf5 export should add axis tag information

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik4ij#36]
in order to interpret axes correctly, it is necessary to add this information. Since this is intended for ilastik use, we should write out vigra-compatible axistags.

**Comment by Tomaz-Vieira** [comment]
I'd go even further and say we should both the vigra axistags as well as the native h5 axis labels via [dimension sacles](http://docs.h5py.org/en/stable/high/dims.html) so that it can also be interpreted by other consumers of h5

**Comment by emilmelnikov** [comment]
It seems that dimension scales are not supported by JHDF5.

**Comment by k-dominik** [comment]
I'll bump this one, as it is an issue with opening the exported data in MoBiE, unfortunately.

**Comment by k-dominik** [comment]
closed via #126
