### ISSUE TITLE
import via maven

### ISSUE THREAD

**Issue by tischi** [ilastik/ilastik4ij#41]
@wolny 

I cannot get this import to work:

```
		<dependency>
			<groupId>org.ilastik</groupId>
			<artifactId>ilastik4ij</artifactId>
			<version>1.7.1</version>
		</dependency>
```

Could it be that version `1.7.1` has not yet been pushed to some repository?

**Comment by imagejan** [comment]
Versions later then `1.6.1-SNAPSHOT` apparently haven't been deployed, due to a missing `ciManagement` entry in the POM that's now required:

https://github.com/ilastik/ilastik4ij/blob/2b9028e41953d54d836437c2751ae586e1b8646b/pom.xml#L68-L70

I submitted #43 as an attempt to fix this.

**Comment by imagejan** [comment]
Yay, [`ilastik4ij-1.7.2-SNAPSHOT`](https://maven.scijava.org/#nexus-search;gav~org.ilastik~ilastik4ij~1.7.2-SNAPSHOT~~) was successfully deployed 😄

**Comment by wolny** [comment]
Ah, so the deployment was done by the Travis job triggered by the merge to master event. Awesome!

**Comment by imagejan** [comment]
Yes: every commit to `master` will trigger a `SNAPSHOT` deployment; every release tag (created by running [`release-version.sh`](https://github.com/scijava/scijava-scripts/blob/master/release-version.sh)) will deploy the respective release version.
