### ISSUE TITLE
Running a trained model in FIJI

### ISSUE THREAD

**Issue by IgnaczAttila** [ilastik/ilastik4ij#75]
Until a recent FIJI update, I was able to run Ilastik Pixel classification prediction from FIJI, simply by selecting it in the Plugins menu. Now, however, I get an errormessage in FIJI when I try the same thing. This is the Log that pops up:

![Log](https://user-images.githubusercontent.com/77971177/105707551-68ab3480-5f13-11eb-97f2-2cfb31b9092c.png)

**Comment by k-dominik** [comment]
Dear @IgnaczAttila,

so sorry you ran into this. We had an inconsistency in some versions of ilastik and the plugin previously supported the less abundant one. Now we have changed that. There is only two suggestions I can make:

* update to the next stable version of ilastik (in your case ilastik 1.3.3post3), or
* use the [previous version (1.8.0) of the plugin](https://sites.imagej.net/Ilastik/plugins/ilastik4ij-1.8.0.jar-20201013214043).

Again sorry that you have been affected by this.


P.S.: Please see the compatibility note under the [the point installation](https://github.com/ilastik/ilastik4ij#installation) in our docs.

**Comment by IgnaczAttila** [comment]
Dear @k-dominik ,

Thank you for the quick reply. Indeed, I just did not read the compatibility note. Now, I updated Ilastik to 1.3.3post3 and it works again.

Thanks
