### ISSUE TITLE
Object classification macro recording does not work

### ISSUE THREAD

**Issue by tischi** [ilastik/ilastik4ij#81]
@k-dominik @wolny 
The macro recording for the object classification does not record the parameters for me, but only:
```
run("Run Object Classification Prediction");
```

**Comment by k-dominik** [comment]
cannot reproduce this - for me it records. Could you say more what you were doing?

**Comment by tischi** [comment]
I think the issue is that the properly recorded macro command only appears after the whole thing returned properly.
Since it crashed for me, the macro was never recorded. 
I don't remember now where above recorded line came from.
