### ISSUE TITLE
Configure ilastik executable location - not working on OSX (for me)

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik4ij#96]
When I try to configure the executable location, I get the good old folder chooser. I think it is now sufficient to specify the "ilastik-xy.app", in principle. However, for me... I cannot select it:

![Screenshot 2022-06-01 at 10 59 39](https://user-images.githubusercontent.com/24434157/171368545-a26e3e79-1e49-4142-86c2-b15bf2a0f46d.png)

https://github.com/ilastik/ilastik4ij/blob/5d37b8da3be1d9d8d1b55e8454ae6c5e262a19bc/src/main/java/org/ilastik/ilastik4ij/ui/IlastikOptions.java#L44-L46

I'm on OSX Monterey, not sure if this issue is exclusive to newer OSX versions.

**Comment by emilmelnikov** [comment]
Could be closed too (see https://github.com/ilastik/ilastik4ij/issues/97#issuecomment-1731370563 for details).
