### ISSUE TITLE
Help in configure executable location misleading on osx

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik4ij#97]
since we know the internal structure of the ilastik app, we only require users to specify the path to ilastik.app

The current "hint" string on OSX specifies the full path:

https://github.com/ilastik/ilastik4ij/blob/5d37b8da3be1d9d8d1b55e8454ae6c5e262a19bc/src/main/java/org/ilastik/ilastik4ij/ui/IlastikOptions.java#L25

reference:
https://github.com/ilastik/ilastik4ij/blob/5d37b8da3be1d9d8d1b55e8454ae6c5e262a19bc/src/main/java/org/ilastik/ilastik4ij/executors/AbstractIlastikExecutor.java#L69-L88

**Comment by emilmelnikov** [comment]
Since directory picker doesn't work as intended on macOS anyway, in https://github.com/ilastik/ilastik4ij/pull/115 we use fill path as a hint, while still accepting "short" bundle path.

@k-dominik It seems that issue could be closed.
